<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KyberDomain\KyberDomain.csproj" />
    <ProjectReference Include="..\KyberKeyManagement\KyberKeyManagement.csproj" />
    <ProjectReference Include="..\KyberLibrary\KyberLibrary.csproj" />
    <ProjectReference Include="..\KyberShared\KyberShared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="ReadLine" Version="2.0.1" />
  </ItemGroup>
</Project>
